import nlp from "compromise";
const stopWords = new Set([
     "Age",
        "Employment status",
        "Income level",
        "Location",
        "Area type",
        "National Savings Certificate (NSC)",
        "Senior Citizen Savings Scheme (SCSS)",
        "Public Provident Fund (PPF)",
        "Recurring Deposit (RD)",
        "Post Office Savings Account (SB)",
       "Age",
        "Employment status",
        "Income level",
        "Location",
        "Area type",
        "National Savings Certificate (NSC)",
        "Senior Citizen Savings Scheme (SCSS)",
        "Public Provident Fund (PPF)",
        "Recurring Deposit (RD)",
        "Post Office Savings Account (SB)",
"Retirement Savings",
        "Investment Options",
        "Age Criteria",
        "Employment Type",
        "Income Category",
        "Geographical Area",
        "Savings Schemes",
        "Tax Benefits",
        "Fixed Deposits",
        "Government Backed Plans",
    "Public Provident Fund (PPF)",
        "National Savings Certificate (NSC)",
        "Senior Citizen Savings Scheme (SCSS)",
        "Post Office Savings Account (SB)",
        "Recurring Deposit (RD)",
        "Age-Specific Investments",
        "Income-Based Plans",
        "Employment Status",
        "Geographical Area Impact",
        "Financial Planning",
     "age",
        "employed",
        "unemployed",
        "male",
        "location",
        "Odisha",
        "Balasore",
        "Bargarh",
        "urban",
        "rural",
        "income",
        "low",
        "moderate",
        "high",
        "Public Provident Fund",
        "PPF",
        "Recurring Deposit",
        "RD",
        "National Savings Certificate",
        "NSC",
        "Senior Citizen Savings Scheme",
        "SCSS",
        "Post Office Savings Account",
        "SB",
    "employed",
        "unemployed",
        "male",
        "location",
        "Odisha",
        "Bargarh",
        "Bhadrak",
        "urban",
        "rural",
        "income",
        "low",
        "moderate",
        "high",
        "Post Office Savings Account",
        "SB",
        "National Savings Certificate",
        "NSC",
        "Recurring Deposit",
        "RD",
        "Senior Citizen Savings Scheme",
        "SCSS",
        "Public Provident Fund",
        "PPF",
    "rural",
    "urban",
    "male",
    "savings",
    "investment",
    "financial_planning",
    "government_schemes",
    "retirement",
    "low_income",
    "moderate_income",
    "high_income",
    "age_group",
    "eligible_schemes",
    "financial_security",
    "income_security",
    "Post Office Savings Account (SB)",
            "Public Provident Fund (PPF)",
            "Senior Citizen Savings Scheme (SCSS)",
     "Post Office Savings Account (SB)",
        "Senior Citizen Savings Scheme (SCSS)",
        "Recurring Deposit (RD)",
        "Mahila Samman Savings Certificate",
        "Monthly Income Scheme (MIS)",
        "National Savings Certificate (NSC)",
        "Public Provident Fund (PPF)",
     "Monthly Income Scheme (MIS)",
    "Recurring Deposit (RD)",
    "National Savings Certificate (NSC)",
    "Mahila Samman Savings Certificate",
    "Public Provident Fund (PPF)",
    "Senior Citizen Savings Scheme (SCSS)",
    "Post Office Savings Account (SB)",
    "high income",
    "low income",
    "moderate income",
    "unemployed",
    "employed",
    "urban area",
    "rural area",
    "female",
    "Angul, Odisha",
    "Balangir, Odisha",
    "age",
    "Post Office Savings Account (SB)",
    "Recurring Deposit (RD)",
    "Senior Citizen Savings Scheme (SCSS)",
    "National Savings Certificate (NSC)",
    "Public Provident Fund (PPF)",
    "Monthly Income Scheme (MIS)",
    "Mahila Samman Savings Certificate",
    "Employed",
    "Unemployed",
    "Urban",
    "Rural",
    "Moderate income",
    "Low income",
    "High income",
    "Balangir",
    "Balasore",
    "Female",
    "Age-specific schemes",
    "PM-KISAN",
    "PMFBY",
    "Kisan Credit Card",
    "PPF",
    "NSC",
    "RD",
    "Soil Health Card",
    "large land",
    "small land",
     "seasonal",
      "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
        "Public Provident Fund (PPF)",
        "Soil Health Card Scheme (SHC)",
        "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "Post Office Savings Account (SB)",
        "Kisan Credit Card (KCC)",
        "Recurring Deposit (RD)",
        "kharif season",
        "rabi season",
         "0.5 acres",
        "1 acre",
        "3 acres",
        "7 acres",
        "15 acres",
        "19 to 25 years",
        "25 to 31 years",
        "31 to 39 years",
        "39 to 54 years",
         "Sukanya Samriddhi Account (SSA)",
        "Post Office Savings Account (SB)",
        "Recurring Deposit (RD)",
        "low income",
        "zero income",
        "student",
        "Angul",
        "Odisha",
        "female",
        "male",
        "age 12",
        "age 13",
        "age 14",
        "age 15",
        "age 16",
        "age 17",
        "age 18",
        "age 19",
        "age 20",
        "age 21",
        "age 22",
        "age 23",
        "age 24",
         "Post Office Savings Account (SB)",
        "Recurring Deposit (RD)",
        "Sukanya Samriddhi Account (SSA)",
        "zero income",
        "low income",
        "student",
        "Recurring Deposit (RD)",
        "Sukanya Samriddhi Account (SSA)",
        "Post Office Savings Account (SB)"
]);

export default function extractKeywords(sentence) {
    const doc = nlp(sentence);
    const terms = doc.terms().out("array");
    const keywords = terms.filter((word) => !stopWords.has(word.toLowerCase()));
    return keywords;
}